apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enclave-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: enclave
  policyTypes:
    - Ingress
    - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/16
    ports:
      - protocol: TCP
        port: 443
